[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/gallery"
  to = "/products"
  status = 301

[[redirects]]
  from = "/en/gallery"
  to = "/en/products"
  status = 301
